hw_app/urls.py
from django.urls import path

from . import views

app_name = 'hw_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('customer/<int:pk>/', views.CustomerView.as_view(), name='customer_page'),
    path('product/<int:pk>/', views.ProductView.as_view(), name='product_page'),
    path('update_product/<int:pk>/', views.UpdateProductView.as_view(), name='update_product'),
    path('orders/year/<int:year>/<int:pk>/', views.AllYearProducts.as_view(), name='yearly_orders'),
    path('orders/monthly/<int:year>/<int:month>/<int:pk>/', views.AllMonthProducts.as_view(), name='monthly_orders'),
    path('orders/week/<int:year>/<int:week>/<int:pk>/', views.AllWeekProducts.as_view(), name='weekly_orders'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hw/', include('hw_app.urls')),
    path('', include('seminar_app.urls', namespace='seminar_app')),
    path('les6/', include('myapp6.urls')),
    # path('__debug__/', include("debug_toolbar.urls")),
]

hw_app/models.py
from django.db import models
from django.urls import reverse


class Customer(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    phone = models.CharField(max_length=10)
    address = models.CharField(max_length=200)
    registered_at = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class CategoryProduct(models.Model):
    category_name = models.CharField(max_length=32)
    category_description = models.TextField()

    def __str__(self):
        return self.category_name


class Product(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(CategoryProduct, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    count = models.IntegerField(default=0)
    added_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='product_image',
                              default='default.png',
                              verbose_name='Изображение')

    objects = models.Manager()

    def get_absolute_url(self):
        return reverse('hw_app:product_page', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, related_name='order')
    total_price = models.DecimalField(max_digits=8, decimal_places=2)
    ordered_at = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    def __str__(self):
        return f'Заказ номер {self.pk} клиента {self.customer}'

hw_app/forms.py
from django import forms

from hw_app import models


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['title', 'description', 'price', 'count', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'count': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }

hw_app/views.py
import logging
from datetime import datetime

from django.http import HttpResponse
from django.views.generic import DetailView, UpdateView
from django.views.generic.dates import MonthArchiveView, WeekArchiveView, ArchiveIndexView, YearArchiveView

from hw_app import models, forms

logger = logging.getLogger(__name__)


def index(request):
    # logger.info('Index page accessed')
    return HttpResponse('<h1>Главная страница!</h1>')


def about(request):
    # logger.info('About page accessed')
    return HttpResponse('<h1>Страница обо мне.</h1>')


class CustomerView(DetailView):
    model = models.Customer
    template_name = 'hw_app/customer_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_date'] = datetime.now()
        return context


class AllProducts(ArchiveIndexView):
    model = models.Order
    date_field = 'ordered_at'
    template_name = 'hw_app/all_products.html'
    allow_future = False
    week_format = '%U'
    year_format = '%Y'

    def get_context_data(self, **kwargs):
        customer = models.Customer.objects.get(pk=self.kwargs.get('pk'))
        orders = super().get_queryset().filter(customer=customer).prefetch_related('products')
        products = set(product for order in orders for product in order.products.values_list('title'))

        context = super().get_context_data(**kwargs)
        context['products'] = products
        context['customer'] = customer

        return context

    def get_queryset(self, **kwargs):
        orders = models.Order.objects.get_queryset().filter(customer=self.kwargs.get('pk'))

        return orders


class AllYearProducts(AllProducts, YearArchiveView):
    pass


class AllMonthProducts(AllProducts, MonthArchiveView):
    pass


class AllWeekProducts(AllProducts, WeekArchiveView):
    pass


class UpdateProductView(UpdateView):
    model = models.Product
    template_name = 'hw_app/update_product.html'
    form_class = forms.ProductUpdateForm


class ProductView(DetailView):
    model = models.Product
    template_name = 'hw_app/product_page.html'

hw_app/templates/hw_app/all_products.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ customer }}</h1>
    {% for product in products %}
        {% for prod in product %}
        	<p>{{ prod }}</p>
        {% endfor %}
    {% endfor %}
{% endblock %}

hw_app/templates/hw_app/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Блог{% endblock %}</title>
</head>
<body>
    {% block content %}
        Контент скоро появится...
    {% endblock %}
    <p> Base.html </p>

</body>
</html>

hw_app/templates/hw_app/customer_page.html
{% extends 'hw_app/base.html' %}

{% block content %}
    <h1>Customer: {{ customer }}</h1>

    <p>Посмотреть заказы:</p>
{% endblock %}

hw_app/templates/hw_app/index.html
{% extends 'base.html' %}

{% block content %}
    <img src="{{ product.image.url }}" alt="{{ product.title }}">
    <p>{{ product.title }}</p>
    <p>{{ product.description }}</p>
    <a href="{% url 'hw_app:update_product' product.pk %}">Редактировать товар</a>
{% endblock %}

hw_app/templates/hw_app/product_page.html
{% extends 'base.html' %}

{% block content %}
    <img src="{{ product.image.url }}" alt="{{ product.title }}">
    <p>{{ product.title }}</p>
    <p>{{ product.description }}</p>
    <a href="{% url 'hw_app:update_product' product.pk %}">Редактировать товар</a>
{% endblock %}

hw_app/templates/hw_app/update_product.html
{% extends 'hw_app/base.html' %}

{% block content %}
    <div class="col-6">
        <div class="form-section container">
            <h2>Редактирование товара</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary" type="submit">Обновить</button>
                <a href="{% url 'hw_app:product_page' product.pk %}" class="btn btn-secondary">Отмена</a>
            </form>
        </div>
    </div>
{% endblock %}